### ISSUE TITLE
When signing up, email says "User XXX at example.com ..."

### ISSUE THREAD

**Issue by abeconnelly** [PersonalGenomesOrg/gennotes#20]
When signing up for a new account, I received a confirmation email but the contents of the email received were:

> User abe at example.com has given this as an email address.
> To confirm this is correct, go to ...

(Where '...' was the link back to gennotes).  I used the web site http://gennotes.herokuapp.com.

Also, the 'from' account was 'webmaster@localhost' (via mailgun.org).

Registration and signup worked otherwise.

**Comment by madprime** [comment]
Fixed the Sites object to use "gennotes.herokuapp.com" and "GenNotes" instead of the default "example.com" data.
