### ISSUE TITLE
Check email verified for edits via API

### ISSUE THREAD

**Issue by madprime** [PersonalGenomesOrg/gennotes#9]
For the API views in gennotes_server/views.py we want to enforce sure edits are only coming with users that have verified email address.

Could do this by creating a custom permissions & permissions.py - I think the field that should be checked is the verified field for EmailAddress in allauth.account.models

**Comment by cjb** [comment]
#11 tries to fix this, but it turns out it was already the behavior -- Django allauth doesn't let you log in when your email address is not verified, and IsAuthenticatedOrReadOnly checks whether you're logged in.  So we can just close this.

**Comment by madprime** [comment]
Fixed via #11, and merged.

Wasn't redundant, allauth only checks email=verified through the user login view (i.e. the login form on the website), not other paths to user authentication.
